### ISSUE TITLE
Context composition

### ISSUE THREAD

**Issue by yantonov** [grammarly/perseverance#2]
Context can not be composed by default. 
So if i want to setup some strategies for several tags, it can be done by wrapping with retry macro several times, obviously. 
But the purpose of this library is to simplify retry configuration as i can see, and make it possible to save it in one place, for example.

**Comment by alexander-yakushev** [comment]
@yantonov Sorry, this issue slipped through my notifications, only saw it now.

Do you mean being able to specify multiple strategies for different tags? I considered this possibility, but couldn't come up with the proper syntax for it. Right now it is:
```clojure
(retry {options} & body)
```
Perhaps, the macro could also handle the case like
```clojure
(retry [options] & body)
```
Where `options` is a vector of maps. What do you think?

**Comment by yantonov** [comment]
Yeah, it would be nice. Expressiveness will not decrease; flexibility, obviously, will be improved; code still remains short and descriptive.
One thing to note: in simple scenario, its convenient not to use vector.
I mean (just thinking about it) macro accepts list of arguments where last argument is body (no needs to create vector to wrap single element in typical case).

**Comment by alexander-yakushev** [comment]
I meant that the macro could accept both a single vector of maps or a single map.

**Comment by yantonov** [comment]
Yes, it seems, explicit vector is more idiomatic way.
